###
POST http://114.80.110.197/testmobileapi/json/reply/GetTakeSeeStaffEvaluationStatRequest
Content-Type: application/json
cityen: sz
platform: android

{"dayCount":-7,"pageCount":1,"pageIndex":1,"propId":"12082314393137CFD9843F1C33B98CDC"}

### 注册
POST http://api.vikingship.xyz/api/users
Content-Type: application/json

{"email": "642464144@qq.com", "password": "111111", "nickName": "11111111111"}

### 登录
POST http://api.vikingship.xyz/api/user/login
Content-Type: application/json

{"email": "642464144@qq.com", "password": "111111"}

### 获取当前用户登录信息
GET http://api.vikingship.xyz/api/user/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjYwMjIyZDIzOWM3YWIxMjYzYmFiYWE0MSIsImVtYWlsIjoiNjQyNDY0MTQ0QHFxLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJGs3QUp3NzJyRHZjcllEb3RPV1NocXU4Ui9NL2NGcXouWkdFQ2huWVR1ZGF5Nmp1SXpvR2YuIiwibmlja05hbWUiOiIxMTExMTExMTExMSIsInJvbGUiOnsiX2lkIjoiNWU2MDY5OGJkYjYwZjY0YjU3ZTM2MTMzIiwibmFtZSI6Im5vcm1hbFVzZXIiLCJfX3YiOjAsImNyZWF0ZWRBdCI6IjIwMjAtMDMtMDVUMDI6NTI6NTkuODA4WiIsImFjY2VzcyI6InVzZXIifSwiX192IjowLCJjb2x1bW4iOiI2MDIyMmQyMzljN2FiMTI2M2JhYmFhNDIiLCJjcmVhdGVkQXQiOiIyMDIxLTAyLTA5VDA2OjM1OjE1Ljc2MVoifSwiZXhwIjoxNjEzNDU3NjE4LCJpYXQiOjE2MTI4NTI4MTh9.vFRcXBQDKxrFtitrsgHm82YNwr_M8K7Ri0OObtJ5ljA

### 专栏详情
GET http://api.vikingship.xyz/api/columns/5f3e86d62c56ee13bb83096c

### 专栏列表
GET http://api.vikingship.xyz/api/columns?currentPage=1&pageSize=3



### 当前气象数据
POST http://119.3.177.188:8080/api/web/sidebar/getmeteodata

### 获取设备Bar信息
POST http://119.3.177.188:8080/api/web/sidebar/getdevicesinfo

### 获取设备状态Bar信息
POST http://119.3.177.188:8080/api/web/sidebar/getdevicestatusinfo
Content-Type: application/json

{"deviceTypeCode": 0}

###
POST http://119.3.177.188:8080/api/web/device/getpvstringdetail
Content-Type: application/json

{"deviceId": "120b2494-e4a0-43d7-a1cf-f5f74f0d885e"}

###
POST http://114.80.110.197/testpassportjava/json/reply/CouponUserToCodeRequest
Content-Type: application/json

{"cityCode":"022","sharingCode":"8LAepSQL2bsRBIuL9/GF+w=="}

###
POST http://114.80.110.197/testpassportjava/json/reply/CouponRelationRequest
Content-Type: application/json

{"couponId":"9CA52F20","cityCode":"022","endTime":"2021-05-12T14:00:00.000+0800","appName":"APP_iOS","userId":"U100074064","remark":"{\"estateName\":\"彭晨燕彭晨燕彭晨燕彭晨燕彭晨燕彭晨燕彭晨燕彭晨燕\",\"propertyType\":\"办公楼\",\"estateImage\":\"https:\\\/\\\/pic.centanet.com\\\/tianjin\\\/postimage\\\/xinfang\\\/20200826\\\/0473af7c7762a579242f8c4a32048ed5.jpg\",\"couponContent\":\"￥3000\",\"couponTitle\":\"购房优惠券\",\"estateId\":\"10594\"}","source":"XINFANG","UserToken":"-VQwR4VstNo-xuINdcw\/Ur7AVpj93BUzudA\/zZvwgDYXdJffBWn6MrATCijzOH3kQPckbNzBEUfTg\/YNYDvGiM\/x-KohtTkINm0O3kjXMkYEXA\/L5Kbye-jjFYSUn-wd","CityCode":"022"}